# Generated by Django 4.2.7 on 2023-11-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_financialdata_debt_to_asset_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdata',
            name='month_name',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='January', max_length=255),
        ),
    ]
